version: '3.6'
services:
  postgres:
    image: postgres:latest
    container_name: full_db
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      fullstack:
        ipv4_address: 10.10.10.3

  mysql:
    image: mysql:5.7
    container_name: mysql_test
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=${TEST_DB_NAME}
      - MYSQL_USER=${TEST_DB_USER}
      - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TEST_DB_ROOT_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      fullstack:
        ipv4_address: 10.10.10.4

volumes:
  database_postgres:
  database_mysql:

networks:
  fullstack:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
